config/routes.rb
Scabies::Application.routes.draw do
  resources :projects do
    resources :bugs
  end

  resources :user

  match '/signup',    :controller => 'user', :action => 'new'
  match '/reset',     :controller => 'user', :action => 'reset'
  match '/dashboard', :controller => 'user', :action => 'show'
  match '/login',     :controller => 'user', :action => 'index'
  match '/logout',    :controller => 'user', :action => 'logout'

  root :to => "user#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name, :permalink
  validates_uniqueness_of :permalink
  validates_format_of :permalink, :with => /^[a-z0-9\-_]+$/

  has_many :bugs, :dependent => :destroy
  belongs_to :admin, :class_name => "User"
  has_and_belongs_to_many :users

  def to_param
    return permalink unless permalink.blank?
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :login_required

  # GET /projects
  # GET /projects.xml
  def index
    @user = get_current_user
    @projects = @user.projects + Project.find_all_by_admin_id(@user)
    @projects.uniq!

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find_by_permalink(params[:id])
    redirect_to project_bugs_url(params[:id])
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @user = get_current_user
    @project = Project.new
    @admin = @user
    @users = User.find_all_without_user(@user)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find_by_permalink(params[:id])
    @user = get_current_user
    @admin = @project.admin
    @users = User.find_all_without_user(@admin)
    if @project.nil?
      redirect_to(projects_url, :notice => 'Specified project does not exist')
    elsif @project.admin != @user
      redirect_to(project_bugs_url(@project), :notice => 'You cannot edit this project')
    end
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    @user = get_current_user
    @project.admin = @user
    @project.users << @user
    @project.permalink = @project.permalink.parameterize

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find_by_permalink(params[:id])

    params[:project][:permalink] = params[:project][:permalink].parameterize

    if !params[:project][:user_ids]
      params[:project][:user_ids] = []
    end
    params[:project][:user_ids] << @project.admin.id.to_s

    @project.users.each do |u|
      if !params[:project][:user_ids].include?(u.id.to_s)
        u.projects.delete(@project)
      end
    end

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(project_url(@project), :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @user = get_current_user
    @project = Project.find_by_permalink(params[:id])

    respond_to do |format|
      if @project and @project.admin == @user
        @project.destroy
        format.html { redirect_to(projects_url) }
        format.xml  { head :ok }
      else
        format.html { redirect_to(projects_url, :notice => 'Specified project does not exist') }
      end
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_details.html.erb
<h2>Project</h2>
<%= link_to 'Edit Project Details', edit_project_path(@project) if @project.admin == @user %>
<p>
<b>Project:</b> <br />
<%= @project.name %>
</p>
<b>Description:</b> <br />
<%= @project.description %>
</p>
<b>Admin:</b> <br />
<%= @project.admin.login + " <" + @project.admin.email + ">" %>
</p>
<b>Project members:</b> <br />
<%= @project.users.size %>
</p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <% if @admin %>
    <!-- Disable changing admin user
    <div class="field">
      <%# f.label :admin %><br />
      <%# f.collection_select :admin_id, @users, :id, :email, { :selected => @project.admin_id } %>
    </div>
    -->
    <% if @users.size > 0 %>
    <div class="field">
      <%= f.label :users %><br />
      <%= f.collection_select :user_ids, @users, :id, :email, { :selected =>  @project.user_ids }, { "multiple" => true, "size" => 10 } %>
    </div>
    <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Delete Project', @project, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="column grid_7">
<h2>Projects</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Outstanding Bugs</th>
    <th>Total Bugs</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.name, project %></td>
    <td><%= project.description %></td>
    <td align="center"><%= project.bugs.active_bugs.size %></td>
    <td align="center"><%= project.bugs.size %></td>
  </tr>
<% end %>
</table>
</div>

<div class="column grid_3">
  <h2>Project Options</h2>
  <%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<!-- Unused: see bugs/index -->