config/routes.rb
Scabies::Application.routes.draw do
  resources :projects do
    resources :bugs
  end

  resources :user

  match '/signup',    :controller => 'user', :action => 'new'
  match '/reset',     :controller => 'user', :action => 'reset'
  match '/dashboard', :controller => 'user', :action => 'show'
  match '/login',     :controller => 'user', :action => 'index'
  match '/logout',    :controller => 'user', :action => 'logout'

  root :to => "user#index"

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  validates_length_of :login, :within => 3..40
  validates_length_of :password, :within => 5..40
  validates_presence_of :login, :email, :name, :password, :password_confirmation, :salt
  validates_uniqueness_of :login, :email
  validates_confirmation_of :password
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Invalid email"  

  attr_protected :id, :salt

  has_and_belongs_to_many :watched_bugs, :class_name => "Bug", :join_table => "users_watched_bugs"
  has_and_belongs_to_many :projects

  scope :find_all_without_user, lambda{|user| user ? {:conditions => ["id != ?", user.id]} : {} }

  attr_accessor :password, :password_confirmation

  def self.authenticate(login, pass)
    u=find(:first, :conditions=>["login = ?", login])
    return nil if u.nil?
    return nil if User.encrypt(pass, u.salt)!=u.hashed_password
    return u
    nil
  end

  def password=(pass)
    @password=pass
    self.salt = User.random_string(10) if !self.salt?
    self.hashed_password = User.encrypt(@password, self.salt)
  end

  def send_new_password
    new_pass = User.random_string(10)
    self.password = self.password_confirmation = new_pass
    self.save
    Notifications.deliver_forgot_password(self.email, self.login, new_pass)
  end

  protected

  def self.encrypt(pass, salt)
    Digest::SHA1.hexdigest(pass+salt)
  end

  def self.random_string(len)
    #generat a random password consisting of strings and digits
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(len) { |i| newpass << chars[rand(chars.size-1)] }
    return newpass
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :login_required, :only=>['edit', 'update', 'destroy', 'show']

  # GET /user
  def index
    if logged_in?
      redirect_to dashboard_url
    else
      @user = User.new
    end
  end

  # GET /user/1
  def show
    @user = get_current_user()
    params[:state] = "active" unless params[:state]
    @bugs = Bug.filter(params, {:assignee => @user, :watcher => @user})
  end

  # GET /user/new
  def new
    if logged_in?
      redirect_to dashboard_url
    else
      @user = User.new
    end
  end

  # GET /user/1/edit
  def edit
    @user = get_current_user
  end

  def reset
  end

  # POST /user
  def create
    @user = User.new(params[:user])
    # Are we logging in?
    if !params[:user][:password_confirmation].present?
      if params[:user][:login].present?
        @user = User.authenticate(@user.login, @user.password)
        if @user.nil?
          redirect_to(login_url, :notice => 'Login was unsuccessful.')
        else
          session[:user] = @user.login
          redirect_to_stored
        end

      # Password reset request
      elsif params[:user][:email].present?
        @user = User.find_by_email(params[:user][:email])
        if @user
          if @user.send_new_password.deliver
            redirect_to(login_url, :notice => "A new password has been sent by email.")
          else
            redirect_to(login_url)
          end
        end
      end

    # We are signing up a new account
    else
      if @user.save
        session[:user] = User.authenticate(@user.login, @user.password).login

        redirect_to(dashboard_url, :id => @user.id, :notice => 'Signup was successful.')
      else
        render :action => "new"
      end
    end
  end

  # PUT /user/1
  def update
    if logged_in?
      @user = User.authenticate(get_current_user.login, params[:user][:current_password])

      if params[:user][:password].empty? and params[:user][:password_confirmation].empty?
        params[:user][:password] = params[:user][:current_password]
        params[:user][:password_confirmation] = params[:user][:current_password]
      end
      params[:user].delete :current_password
    end

    if @user
      @user.update_attributes(params[:user])
      if @user.save
        redirect_to(dashboard_url, :id => @user.id,
                    :notice => 'Details updated successfully.')
      else
        render :action => "edit"
      end
    else
      render :action => "edit"
    end
  end

  # GET /user/logout
  def logout
    session[:user] = nil
    flash[:message] = 'Logged out'
    redirect_to login_url
  end

  # DELETE /user/1
  def destroy
    #@user = User.find(params[:id])

    #respond_to do |format|
    #  format.html { redirect_to(user_index) }
    #end
  end
end

app/views/user/_form.html.erb
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if mode == "login" or mode == "signup" %>
  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
<% end %>

<% if mode == "signup" %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
<% end %>

<% if mode == "signup" or mode == "edit" %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<% end %>

<% if mode == "signup" or mode == "login" %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
<% end %>

<% if mode == "edit" %>
  <div class="field">
    <%= f.label "Current Password" %><br />
    <%= password_field_tag "user[current_password]" %>
  </div>
  <div class="field">
    <%= f.label "New Password" %><br />
    <%= f.password_field :password %>
  </div>
<% end %>

<% if mode == "signup" or mode == "edit" %>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
<% end %>

<div class="actions">
  <% if mode == "signup" %>
    <%= f.submit "Signup" %>
  <% elsif mode == "login" %>
    <%= f.submit "Login" %>
  <% elsif mode == "edit" %>
    <%= f.submit "Update" %>
  <% end %>
</div>

app/views/user/edit.html.erb
<h1>Edit Account</h1>

<%= form_for(@user, :url => user_path) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f, :mode => "edit"} %>
<% end %>

<%= link_to 'Back', user_path(@user) %>

app/views/user/index.html.erb
<div class="column grid_7">
<h1>Login</h1>

<%= form_for(@user, :url => user_index_path) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f, :mode => "login"} %>
<% end %>
Not Registered? <%= link_to "Sign Up", signup_path %> <br />
Forgot your password? <%= link_to "Reset Password", reset_path %>
</div>

<div class="column grid_3">
</div>

app/views/user/new.html.erb
<div class="column grid_7">
<h1>Signup for Scabies</h1>

<p>Once you've got scabies, you'll wonder how you ever lived without it!</p>

<%= form_for(@user, :url => user_index_path) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f, :mode => "signup"} %>
<% end %>
</div>

<div class="column grid_3">
</div>

app/views/user/reset.html.erb
<h1>Reset Password</h1>

<%= form_for(:user, :url => user_index_path) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit "Reset Password" %>
  </div>

<% end %>

Not Registered? <%= link_to "Sign Up", signup_path %> <br />
Remember your password? <%= link_to "Login", login_path %>

app/views/user/show.html.erb
<div class="column grid_7">
  <%= link_to "Active", {:state => "active"} %> |
  <%= link_to "Assigned", {:state => "assigned"} %> |
  <%= link_to "Open", {:state => "opened"} %> |
  <%= link_to "Resolved", {:state => "resolved"} %> |
  <%= link_to "Closed", {:state => "closed"} %> |
  <%= link_to "Watching", {:watching => "1"} %> |
  <%= link_to "All", {:state => "all"} %>

  <%= render :partial => 'bugs/list', :locals => { :show_project => true } %>

</div>

<div class="column grid_3">
<h2>My Account</h2>

<%= link_to 'Edit Account Details', edit_user_path(@user) %>

<p>
Login: <%= @user.login %><br/>
Name: <%= @user.name %><br/>
Email: <%= @user.email %>
</p>
</div>