config/routes.rb
Scabies::Application.routes.draw do
  resources :projects do
    resources :bugs
  end

  resources :user

  match '/signup',    :controller => 'user', :action => 'new'
  match '/reset',     :controller => 'user', :action => 'reset'
  match '/dashboard', :controller => 'user', :action => 'show'
  match '/login',     :controller => 'user', :action => 'index'
  match '/logout',    :controller => 'user', :action => 'logout'

  root :to => "user#index"

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :project
  belongs_to :creator, :class_name => "User"
  belongs_to :assignee, :class_name => "User"
  has_and_belongs_to_many :watchers, :class_name => "User", :join_table => "users_watched_bugs"
  has_many :comments, :dependent => :destroy

  scope :by_assignee, lambda { |*user| {:conditions => {:assignee_id => user}} }
  scope :by_watcher, lambda { |*watcher|
    {
      :joins => :watchers,
      :conditions => ["users_watched_bugs.user_id = #{watcher[0].id}"]
    }
  }
  scope :active_bugs, :conditions => ["state != ?", "closed"]


  attr_protected :state_event
  state_machine :initial => :new do

    event :assign do
      transition :new => :assigned
    end
    state :assigned do
      validates_presence_of :assignee
    end

    event :reassign do
      transition :assigned => :new
      transition :opened => :new
    end
    after_transition :to => :new do |bug, transition|
      bug.assignee = nil
      bug.save
    end

    event :open do
      transition :assigned => :opened
    end

    event :resolve do
      transition :opened => :resolved
    end

    event :close do
      transition :resolved => :closed
    end

    event :reject do
      transition :resolved => :opened
    end

    event :reopen do
      transition :closed => :new
    end

  end

  def valid_events(user)
    valid = []

    # Ensure the project admin can always modify bug state
    if user == self.project.admin
      return self.state_transitions.collect { |t| t.event }
    end

    # Otherwise restrict events to relevant users
    self.state_transitions.each do |transition|
      case transition.event
      when :assign, :reassign
        valid << transition.event
      when :open, :resolve
        valid << transition.event if user == self.assignee
      when :close, :reject, :reopen
        valid << transition.event if user == self.creator
      end
    end
    valid
  end

  def verify_next_event(event_name, user)
    events = valid_events(user)
    events.each do |event|
      if event.to_s == event_name
        return event
      end
    end
    nil
  end

  def generate_state_comment(user, from, to)
    if from.nil?
      text = "*#{user.login}* created *#{to}* bug _#{self.name}_."
    else
      text = "*#{user.login}* changed bug state from *#{from}* to *#{to}*."
    end

    comment = Comment.new(:user_id => user.id, :bug_id => self.id, :content => text)
    self.comments << comment
  end

  def self.valid_state(state)
    return Bug.state_machine.states.keys.include?(state.to_sym)
  end

  def self.filter(params, options = {})
    scope = Bug.scoped({})

    if params[:watching]
      scope = scope.by_watcher(options[:watcher])
    else
      scope = scope.scoped :conditions => {:assignee_id => options[:assignee]} if options[:assignee]
      scope = scope.scoped :conditions => {:project_id => options[:project]} if options[:project]
    end


    if params[:state]
      if self.valid_state(params[:state])
        scope = scope.scoped :conditions => {:state => params[:state]}
      else
        case params[:state]
        when "active"
          scope = scope.active_bugs
        when "all"
          # don't scope if we want all bugs
        end
      end
    end

    if params[:sort] and Bug.column_names.include?(params[:sort])
      direction = %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
      scope = scope.scoped :order => (params[:sort] + " " + direction)
    end
    scope
  end

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_filter :login_required

  # GET projects/1/bugs
  # GET projects/1/bugs.xml
  def index
    @project = Project.find_by_permalink(params[:project_id])
    @user = get_current_user

    respond_to do |format|
      if @project and @project.users.exists?(@user)

        params[:state] = "active" unless params[:state]
        @bugs = Bug.filter(params, {:project => @project})

        format.html # show.html.erb
        format.xml  { render :xml => @project }
      else
        format.html { redirect_to(projects_url, :notice => 'Specified project does not exist') }
      end
    end
  end

  # GET projects/1/bugs/1
  # GET projects/1/bugs/1.xml
  def show
    @user = get_current_user
    @project = Project.find_by_permalink(params[:project_id])
    @bug = @project.bugs.find_by_id(params[:id])
    @users = User.all
    @comments = @bug.comments.order("created_at DESC")
    @watchers = @bug.watchers
    @watcher = @bug.watchers.find_by_id(@user.id)

    respond_to do |format|
      if @project and @bug and @project.users.exists?(@user)
        format.html # show.html.erb
        format.xml  { render :xml => @bug }
      else
        format.html { redirect_to(projects_url, :notice => 'Specified bug does not exist') }
      end
    end
  end

  # GET /projects/1/bugs/new
  # GET projects/1/bugs/new.xml
  def new
    @user = get_current_user
    @project = @user.projects.find_by_permalink(params[:project_id])
    @bug = Bug.new(:project => @project, :creator => @user)

    respond_to do |format|
      if @project and @bug
        format.html # new.html.erb
        format.xml  { render :xml => @bug }
      else
        format.html { redirect_to(projects_url, :notice => 'Specified project does not exist') }
      end
    end
  end

  # GET /projects/1/bugs/1/edit
  def edit
    @project = Project.find_by_permalink(params[:project_id])
    @bug = Bug.find_by_id(params[:id])
    @user = get_current_user

    respond_to do |format|
      if @project and @bug and @project.users.exists?(@user)
        @users = @project.users
        format.html # edit.html.erb
      else
        format.html { redirect_to(projects_url, :notice => 'Specified bug does not exist') }
      end
    end
  end

  # POST /projects/1/bugs
  # POST /projects/1/bugs.xml
  def create
    @project = Project.find_by_permalink(params[:project_id])
    @bug = Bug.new(params[:bug])
    @bug.project = @project
    @bug.creator = get_current_user

    respond_to do |format|
      if @bug.save
        @bug.generate_state_comment(@bug.creator, nil, @bug.state)
        format.html { redirect_to(project_bug_url(@project, @bug),
                      :notice => 'Bug was successfully created.') }
        format.xml  { render :xml => @bug, :status => :created, :location => @bug }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bug.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT projects/1/bugs/1
  # PUT projects/1/bugs/1.xml
  def update
    @project = Project.find_by_permalink(params[:project_id])
    @bug = Bug.find(params[:id])
    @user = get_current_user

    if params[:bug][:watcher_id]
      @watcher = @project.users.find_by_id(params[:bug][:watcher_id])
      params[:bug].delete :watcher_id

      if @bug.watchers.include?(@watcher)
        @bug.watchers.delete(@watcher)
      else
        @bug.watchers << @watcher unless @watcher.nil?
      end
    end

    if params[:bug][:comment]
      @comment = Comment.new()
      @comment.user = @user
      @comment.content = RedCloth.new(params[:bug][:comment][:content]).to_html
      @bug.comments << @comment
      params[:bug].delete :comment
    end

    if params[:bug][:state]
      if @bug.state != params[:bug][:state]
        render :action => "show"
        return
      else
        params[:bug].delete :state
      end
    end

    if params[:bug][:next_event]
      next_event = @bug.verify_next_event(params[:bug][:next_event], @user)
      if next_event.nil?
        render :action => "show"
        return
      end
      params[:bug].delete :next_event
    end

    if @bug.update_attributes(params[:bug])
      if next_event
        transition = @bug.state_transitions.find { |t| t if t.event == next_event }
        @bug.fire_events(next_event)
        @bug.generate_state_comment(@user, transition.from, transition.to)
      end

      redirect_to(project_bug_url(@project, @bug),
                  :notice => 'Bug was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE projects/1/bugs/1
  # DELETE projects/1/bugs/1.xml
  def destroy
    @project = Project.find_by_permalink(params[:project_id])
    @bug = Bug.find_by_id(params[:id])

    respond_to do |format|
      if @project and @bug and @project.bugs.exists?(@bug)
        @bug.destroy
        format.html { redirect_to(project_url(@project)) }
        format.xml  { head :ok }
      else
        format.html { redirect_to(projects_url, :notice => 'Specified bug does not exist') }
      end
    end
  end

end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<%= form_for([@project, @bug]) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.hidden_field :project_id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/_list.html.erb
<%
    title = bug_list_title if local_assigns[:title].nil?
    show_project = false if local_assigns[:show_project].nil?
%>

<h2><%= title %></h2>

<table>
      <tr>
        <th><%= sortable "id", "ID" %></th>
        <% if show_project == true %>
        <th><%= sortable "project_id", "Project" %></th>
         <% end %>
        <th>Name</th>
        <th>Description</th>
        <th><%= sortable "state" %></th>
        <th><%= sortable "created_at" %></th>
        <th><%= sortable "updated_at" %></th>
      </tr>
  <% @bugs.each do |bug| %>
    <tr>
      <td><%= link_to bug.id, project_bug_path(bug.project.permalink, bug) %></td>
      <% if show_project == true %>
      <td> <%= link_to bug.project.name, project_path(bug.project) %> </td>
      <% end %>
      <td><%= link_to bug.name, project_bug_path(bug.project.permalink, bug) %></td>
      <td><%= bug.description %></td>
      <td><%= bug.state %></td>
      <td><%= bug.created_at.to_s(:comment_format) %></td>
      <td><%= bug.updated_at.to_s(:comment_format) %></td>
    </tr>
  <% end %>
</table>

app/views/bugs/_new.html.erb
<%= f.collection_select :assignee_id, @users, :id, :login, { :selected =>  @user.id } %>

app/views/bugs/edit.html.erb
<h1>Editing bug</h1>

<%= render 'form' %>

<%= link_to 'Cancel', project_bug_path(@project, @bug) %>

app/views/bugs/index.html.erb
<div class="column grid_7">
  <%= link_to "Active", {:state => "active"} %> |
  <%= link_to "New", {:state => "new"} %> |
  <%= link_to "Assigned", {:state => "assigned"} %> |
  <%= link_to "Open", {:state => "opened"} %> |
  <%= link_to "Resolved", {:state => "resolved"} %> |
  <%= link_to "Closed", {:state => "closed"} %> |
  <%= link_to "All", {:state => "all"} %>
  <%= render :partial =>'list', :locals => { } %>
</div>

<div class="column grid_3">
  <%= render :partial =>'projects/details' %>
  <%= link_to 'New Bug', new_project_bug_path(@project) %> <br />
</div>

app/views/bugs/new.html.erb
<h1><%= "#{@project.name.to_s}" %> -- New bug</h1>

<%= render 'form' %>

<%= link_to 'Back', project_path(@project) %>

app/views/bugs/show.html.erb
<div class="row">
  <div class="column grid_7">
    <%= link_to "Back to #{@project.name}", project_path(@project) %>

    <p>
    <b>Name:</b>
    <%= @bug.name %>
    </p>

    <p>
    <b>Description:</b>
    <td><%= RedCloth.new(@bug.description).to_html.html_safe %></td>
    </p>

    <p>
    <b>State:</b>
    <%= @bug.state %>
    </p>

    <p>
    <% @bug.valid_events(@user).each do |event| %>

      <%= form_for([@project, @bug]) do |f| %>
        <%= f.hidden_field :state %>
        <%= hidden_field_tag "bug[next_event]", event.to_s %>
        <%=
          begin
            render :partial => "#{@bug.state.to_s}", :locals => {:f => f}
          rescue
            nil
          end
        %>
        <%= f.submit "#{event.to_s.capitalize}" %>
      <% end %>

    <% end %>
    </p>

    <p><b>Comments:</b></p>

    <%= form_for([@project, @bug]) do |f| %>
      <div class="field">
        <%= text_area "bug[comment]", "content", :rows => 10, :cols => 80 %>
      </div>
      <div class="field">
        <%= f.submit "Post Comment" %>
      </div>
    <% end %>

    <p>
    <b>Filter:</b> Bug Events | User Comments | All
    </p>

    <table>
      <tr>
        <th>User</th>
        <th>Comment</th>
        <th>Date</th>
      </tr>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.user.name %></td>
          <td><%= RedCloth.new(comment.content).to_html.html_safe %></td>
          <td><%= comment.created_at.to_s(:comment_format) %></td>
        </tr>
      <% end %>
    </table>

  </div>

  <div class="column grid_3">
    <p>
    <b>Created by:</b> <br />
    <%= @bug.creator.login.to_s + " <" + @bug.creator.email.to_s + ">" %>
    </p>

    <p>
    <b>Assigned to:</b> <br />
    <%= @bug.assignee.present? ? @bug.assignee.login.to_s + " <" + @bug.assignee.email.to_s + ">" : "Unassigned" %>
    </p>

    <p>
    <b>Watchers:</b> <br />
    <%= @watchers.present? ? @watchers.collect{ |b| b.login }.join(", ") : "None" %>
    <%= form_for([@project, @bug]) do |f| %>
      <div class="field">
        <%= hidden_field_tag "bug[watcher_id]", @user.id %>
        <%= f.submit @watcher.present? ? "Stop Watching" : "Watch" %>
      </div>
    <% end %>
    </p>

    <%= link_to 'Edit Bug Details', edit_project_bug_path(@project, @bug) if @bug.creator == @user %>
    <br />
    <%= link_to 'Delete Bug', project_bug_path(@project, @bug), :confirm => 'Are you sure?', :method => :delete if @bug.creator == @user %><br />
  </div>

</div>
<div class="row">
  <div class="column grid_10">
  </div>
</div>